[build]
  # This will be your default build command.
  command = "npm run build"
  # This is the directory that you are publishing from.
  publish = "dist"
  functions = "netlify/functions/"

[functions.read-sheets]
  external_node_modules = ["dotenv", "googleapis"]
